CREATE TABLE IF NOT EXISTS Posts (PostId INTEGER PRIMARY KEY, PostTitle TEXT, PostContent TEXT);

CREATE TABLE IF NOT EXISTS Users (UserId INTEGER PRIMARY KEY, UserName TEXT, UserLogin TEXT, UserPassword TEXT);